name: rtdl
channels:
- https://conda.anaconda.org/conda-forge
- nodefaults
dependencies:
- black=23.10.1
- flit=3.9.0
- isort=5.12.0
- jupyterlab<5
- mypy=1.6.1
- numpy=1.19.5
- pdoc=14.1.0
- pip<24
- pytest=7.4.2
- python=3.8
- pytorch=1.8.0
- scikit-learn=1.0.2
- ruff=0.1.5
- tomli=2.0.1
- tqdm=4.66.1
- xdoctest=1.1.2
- pip:
  - delu==0.0.23
